/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MONITOR"
 * 	found in "monitor.asn"
 */

#ifndef	_AlertIdBitmap_H_
#define	_AlertIdBitmap_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlertIdBitmap */
typedef OCTET_STRING_t	 AlertIdBitmap_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AlertIdBitmap_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AlertIdBitmap;
asn_struct_free_f AlertIdBitmap_free;
asn_struct_print_f AlertIdBitmap_print;
asn_constr_check_f AlertIdBitmap_constraint;
ber_type_decoder_f AlertIdBitmap_decode_ber;
der_type_encoder_f AlertIdBitmap_encode_der;
xer_type_decoder_f AlertIdBitmap_decode_xer;
xer_type_encoder_f AlertIdBitmap_encode_xer;
oer_type_decoder_f AlertIdBitmap_decode_oer;
oer_type_encoder_f AlertIdBitmap_encode_oer;
per_type_decoder_f AlertIdBitmap_decode_uper;
per_type_encoder_f AlertIdBitmap_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AlertIdBitmap_H_ */
#include <asn_internal.h>
