/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MONITOR"
 * 	found in "monitor.asn"
 */

#ifndef	_AlertData_H_
#define	_AlertData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlertData */
typedef OCTET_STRING_t	 AlertData_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AlertData_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AlertData;
asn_struct_free_f AlertData_free;
asn_struct_print_f AlertData_print;
asn_constr_check_f AlertData_constraint;
ber_type_decoder_f AlertData_decode_ber;
der_type_encoder_f AlertData_encode_der;
xer_type_decoder_f AlertData_decode_xer;
xer_type_encoder_f AlertData_encode_xer;
oer_type_decoder_f AlertData_decode_oer;
oer_type_encoder_f AlertData_encode_oer;
per_type_decoder_f AlertData_decode_uper;
per_type_encoder_f AlertData_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AlertData_H_ */
#include <asn_internal.h>
