/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MONITOR"
 * 	found in "monitor.asn"
 */

#include "RVSPOSITION.h"

static int
memb_timeStamp_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 2147483647)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_gpsStatus_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_timeStamp_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..2147483647) */,
	-1};
static asn_per_constraints_t asn_PER_memb_timeStamp_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 31, -1,  0,  2147483647 }	/* (0..2147483647) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_gpsStatus_constr_4 CC_NOTUSED = {
	{ 1, 1 }	/* (0..3) */,
	-1};
static asn_per_constraints_t asn_PER_memb_gpsStatus_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_RVSPOSITION_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RVSPOSITION, wayPoint),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RVSWAYPOINT,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"wayPoint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RVSPOSITION, timeStamp),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_timeStamp_constr_3, &asn_PER_memb_timeStamp_constr_3,  memb_timeStamp_constraint_1 },
		0, 0, /* No default value */
		"timeStamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RVSPOSITION, gpsStatus),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_gpsStatus_constr_4, &asn_PER_memb_gpsStatus_constr_4,  memb_gpsStatus_constraint_1 },
		0, 0, /* No default value */
		"gpsStatus"
		},
};
static const ber_tlv_tag_t asn_DEF_RVSPOSITION_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RVSPOSITION_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 1 }, /* timeStamp */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 0 }, /* gpsStatus */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* wayPoint */
};
asn_SEQUENCE_specifics_t asn_SPC_RVSPOSITION_specs_1 = {
	sizeof(struct RVSPOSITION),
	offsetof(struct RVSPOSITION, _asn_ctx),
	asn_MAP_RVSPOSITION_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RVSPOSITION = {
	"RVSPOSITION",
	"RVSPOSITION",
	&asn_OP_SEQUENCE,
	asn_DEF_RVSPOSITION_tags_1,
	sizeof(asn_DEF_RVSPOSITION_tags_1)
		/sizeof(asn_DEF_RVSPOSITION_tags_1[0]), /* 1 */
	asn_DEF_RVSPOSITION_tags_1,	/* Same as above */
	sizeof(asn_DEF_RVSPOSITION_tags_1)
		/sizeof(asn_DEF_RVSPOSITION_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RVSPOSITION_1,
	3,	/* Elements count */
	&asn_SPC_RVSPOSITION_specs_1	/* Additional specs */
};

