/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MONITOR"
 * 	found in "monitor.asn"
 */

#ifndef	_RVSPOSITION_H_
#define	_RVSPOSITION_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RVSWAYPOINT.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RVSPOSITION */
typedef struct RVSPOSITION {
	RVSWAYPOINT_t	 wayPoint;
	long	 timeStamp;
	long	 gpsStatus;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RVSPOSITION_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RVSPOSITION;
extern asn_SEQUENCE_specifics_t asn_SPC_RVSPOSITION_specs_1;
extern asn_TYPE_member_t asn_MBR_RVSPOSITION_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RVSPOSITION_H_ */
#include <asn_internal.h>
