/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MONITOR"
 * 	found in "monitor.asn"
 */

#include "RVSVEHICLEALERT.h"

static int
alertTime_2_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_alertTime_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static asn_oer_constraints_t asn_OER_type_alertTime_constr_2 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_alertTime_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_alertTime_constr_2 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_alertTime_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_alertTime_specs_2 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_alertTime_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_alertTime_2 = {
	"alertTime",
	"alertTime",
	&asn_OP_NativeInteger,
	asn_DEF_alertTime_tags_2,
	sizeof(asn_DEF_alertTime_tags_2)
		/sizeof(asn_DEF_alertTime_tags_2[0]), /* 1 */
	asn_DEF_alertTime_tags_2,	/* Same as above */
	sizeof(asn_DEF_alertTime_tags_2)
		/sizeof(asn_DEF_alertTime_tags_2[0]), /* 1 */
	{ &asn_OER_type_alertTime_constr_2, &asn_PER_type_alertTime_constr_2, alertTime_2_constraint },
	0, 0,	/* No members */
	&asn_SPC_alertTime_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RVSVEHICLEALERT_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RVSVEHICLEALERT, alertTime),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_alertTime_2,
		0,
		{ &asn_OER_memb_alertTime_constr_2, &asn_PER_memb_alertTime_constr_2,  memb_alertTime_constraint_1 },
		0, 0, /* No default value */
		"alertTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RVSVEHICLEALERT, gpsPosition),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RVSPOSITION,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gpsPosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RVSVEHICLEALERT, alertIdBitmap),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_AlertIdBitmap,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"alertIdBitmap"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RVSVEHICLEALERT, alertData),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_AlertData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"alertData"
		},
};
static const ber_tlv_tag_t asn_DEF_RVSVEHICLEALERT_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RVSVEHICLEALERT_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* alertTime */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 1 }, /* alertIdBitmap */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, -1, 0 }, /* alertData */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* gpsPosition */
};
static asn_SEQUENCE_specifics_t asn_SPC_RVSVEHICLEALERT_specs_1 = {
	sizeof(struct RVSVEHICLEALERT),
	offsetof(struct RVSVEHICLEALERT, _asn_ctx),
	asn_MAP_RVSVEHICLEALERT_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RVSVEHICLEALERT = {
	"RVSVEHICLEALERT",
	"RVSVEHICLEALERT",
	&asn_OP_SEQUENCE,
	asn_DEF_RVSVEHICLEALERT_tags_1,
	sizeof(asn_DEF_RVSVEHICLEALERT_tags_1)
		/sizeof(asn_DEF_RVSVEHICLEALERT_tags_1[0]), /* 1 */
	asn_DEF_RVSVEHICLEALERT_tags_1,	/* Same as above */
	sizeof(asn_DEF_RVSVEHICLEALERT_tags_1)
		/sizeof(asn_DEF_RVSVEHICLEALERT_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RVSVEHICLEALERT_1,
	4,	/* Elements count */
	&asn_SPC_RVSVEHICLEALERT_specs_1	/* Additional specs */
};

