/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MONITOR"
 * 	found in "monitor.asn"
 */

#ifndef	_RVSVEHICLEALERT_H_
#define	_RVSVEHICLEALERT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "RVSPOSITION.h"
#include "AlertIdBitmap.h"
#include "AlertData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RVSVEHICLEALERT */
typedef struct RVSVEHICLEALERT {
	unsigned long	 alertTime;
	RVSPOSITION_t	 gpsPosition;
	AlertIdBitmap_t	 alertIdBitmap;
	AlertData_t	 alertData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RVSVEHICLEALERT_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_alertTime_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RVSVEHICLEALERT;

#ifdef __cplusplus
}
#endif

#endif	/* _RVSVEHICLEALERT_H_ */
#include <asn_internal.h>
