/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MONITOR"
 * 	found in "monitor.asn"
 */

#include "RVSWGS84POINT.h"

static int
memb_latitude_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -900000000 && value <= 900000000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_longitude_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -1800000000 && value <= 1800000000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_altitude_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -1000 && value <= 8900)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_latitude_constr_2 CC_NOTUSED = {
	{ 4, 0 }	/* (-900000000..900000000) */,
	-1};
static asn_per_constraints_t asn_PER_memb_latitude_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 31, -1, -900000000,  900000000 }	/* (-900000000..900000000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_longitude_constr_3 CC_NOTUSED = {
	{ 4, 0 }	/* (-1800000000..1800000000) */,
	-1};
static asn_per_constraints_t asn_PER_memb_longitude_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1, -1800000000,  1800000000 }	/* (-1800000000..1800000000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_altitude_constr_4 CC_NOTUSED = {
	{ 2, 0 }	/* (-1000..8900) */,
	-1};
static asn_per_constraints_t asn_PER_memb_altitude_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 14,  14, -1000,  8900 }	/* (-1000..8900) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_RVSWGS84POINT_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RVSWGS84POINT, latitude),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_latitude_constr_2, &asn_PER_memb_latitude_constr_2,  memb_latitude_constraint_1 },
		0, 0, /* No default value */
		"latitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RVSWGS84POINT, longitude),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_longitude_constr_3, &asn_PER_memb_longitude_constr_3,  memb_longitude_constraint_1 },
		0, 0, /* No default value */
		"longitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RVSWGS84POINT, altitude),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_altitude_constr_4, &asn_PER_memb_altitude_constr_4,  memb_altitude_constraint_1 },
		0, 0, /* No default value */
		"altitude"
		},
};
static const ber_tlv_tag_t asn_DEF_RVSWGS84POINT_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RVSWGS84POINT_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* latitude */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 1 }, /* longitude */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 0 } /* altitude */
};
asn_SEQUENCE_specifics_t asn_SPC_RVSWGS84POINT_specs_1 = {
	sizeof(struct RVSWGS84POINT),
	offsetof(struct RVSWGS84POINT, _asn_ctx),
	asn_MAP_RVSWGS84POINT_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RVSWGS84POINT = {
	"RVSWGS84POINT",
	"RVSWGS84POINT",
	&asn_OP_SEQUENCE,
	asn_DEF_RVSWGS84POINT_tags_1,
	sizeof(asn_DEF_RVSWGS84POINT_tags_1)
		/sizeof(asn_DEF_RVSWGS84POINT_tags_1[0]), /* 1 */
	asn_DEF_RVSWGS84POINT_tags_1,	/* Same as above */
	sizeof(asn_DEF_RVSWGS84POINT_tags_1)
		/sizeof(asn_DEF_RVSWGS84POINT_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RVSWGS84POINT_1,
	3,	/* Elements count */
	&asn_SPC_RVSWGS84POINT_specs_1	/* Additional specs */
};

