/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MONITOR"
 * 	found in "monitor.asn"
 */

#ifndef	_RVSWGS84POINT_H_
#define	_RVSWGS84POINT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RVSWGS84POINT */
typedef struct RVSWGS84POINT {
	long	 latitude;
	long	 longitude;
	long	 altitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RVSWGS84POINT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RVSWGS84POINT;
extern asn_SEQUENCE_specifics_t asn_SPC_RVSWGS84POINT_specs_1;
extern asn_TYPE_member_t asn_MBR_RVSWGS84POINT_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RVSWGS84POINT_H_ */
#include <asn_internal.h>
