/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DispatcherBody"
 * 	found in "Dispatcher_Body.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_AckRequired_H_
#define	_AckRequired_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AckRequired */
typedef BOOLEAN_t	 AckRequired_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AckRequired;
asn_struct_free_f AckRequired_free;
asn_struct_print_f AckRequired_print;
asn_constr_check_f AckRequired_constraint;
ber_type_decoder_f AckRequired_decode_ber;
der_type_encoder_f AckRequired_encode_der;
xer_type_decoder_f AckRequired_decode_xer;
xer_type_encoder_f AckRequired_encode_xer;
per_type_decoder_f AckRequired_decode_uper;
per_type_encoder_f AckRequired_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AckRequired_H_ */
#include <asn_internal.h>
