/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DispatcherBody"
 * 	found in "Dispatcher_Body.asn"
 * 	`asn1c -gen-PER`
 */

#include "DispatcherBody.h"

static asn_TYPE_member_t asn_MBR_DispatcherBody_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DispatcherBody, applicationId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ApplicationId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"applicationId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DispatcherBody, messageId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MessageId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"messageId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DispatcherBody, eventCreationTime),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventCreationTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"eventCreationTime"
		},
	{ ATF_POINTER, 10, offsetof(struct DispatcherBody, eventID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"eventID"
		},
	{ ATF_POINTER, 9, offsetof(struct DispatcherBody, ulMessageCounter),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UlMessageCounter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ulMessageCounter"
		},
	{ ATF_POINTER, 8, offsetof(struct DispatcherBody, dlMessageCounter),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DlMessageCounter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dlMessageCounter"
		},
	{ ATF_POINTER, 7, offsetof(struct DispatcherBody, ackMessageCounter),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AckMessageCounter,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ackMessageCounter"
		},
	{ ATF_POINTER, 6, offsetof(struct DispatcherBody, ackRequired),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AckRequired,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ackRequired"
		},
	{ ATF_POINTER, 5, offsetof(struct DispatcherBody, applicationDataLength),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ApplicationDataLength,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"applicationDataLength"
		},
	{ ATF_POINTER, 4, offsetof(struct DispatcherBody, dataEncodingType),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataEncodingType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dataEncodingType"
		},
	{ ATF_POINTER, 3, offsetof(struct DispatcherBody, applicationDataProtocolVersion),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ApplicationDataProtocolVersion,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"applicationDataProtocolVersion"
		},
	{ ATF_POINTER, 2, offsetof(struct DispatcherBody, testFlag),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TestFlag,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"testFlag"
		},
	{ ATF_POINTER, 1, offsetof(struct DispatcherBody, result),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Result,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"result"
		},
};
static const int asn_MAP_DispatcherBody_oms_1[] = { 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 };
static const ber_tlv_tag_t asn_DEF_DispatcherBody_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DispatcherBody_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* applicationId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* messageId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* eventCreationTime */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* eventID */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ulMessageCounter */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* dlMessageCounter */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* ackMessageCounter */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* ackRequired */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* applicationDataLength */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* dataEncodingType */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* applicationDataProtocolVersion */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* testFlag */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 } /* result */
};
static asn_SEQUENCE_specifics_t asn_SPC_DispatcherBody_specs_1 = {
	sizeof(struct DispatcherBody),
	offsetof(struct DispatcherBody, _asn_ctx),
	asn_MAP_DispatcherBody_tag2el_1,
	13,	/* Count of tags in the map */
	asn_MAP_DispatcherBody_oms_1,	/* Optional members */
	10, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DispatcherBody = {
	"DispatcherBody",
	"DispatcherBody",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DispatcherBody_tags_1,
	sizeof(asn_DEF_DispatcherBody_tags_1)
		/sizeof(asn_DEF_DispatcherBody_tags_1[0]), /* 1 */
	asn_DEF_DispatcherBody_tags_1,	/* Same as above */
	sizeof(asn_DEF_DispatcherBody_tags_1)
		/sizeof(asn_DEF_DispatcherBody_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DispatcherBody_1,
	13,	/* Elements count */
	&asn_SPC_DispatcherBody_specs_1	/* Additional specs */
};

