/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DispatcherHeader"
 * 	found in "Dispatcher_Header.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_DispatcherMessageLength_H_
#define	_DispatcherMessageLength_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DispatcherMessageLength */
typedef long	 DispatcherMessageLength_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DispatcherMessageLength;
asn_struct_free_f DispatcherMessageLength_free;
asn_struct_print_f DispatcherMessageLength_print;
asn_constr_check_f DispatcherMessageLength_constraint;
ber_type_decoder_f DispatcherMessageLength_decode_ber;
der_type_encoder_f DispatcherMessageLength_encode_der;
xer_type_decoder_f DispatcherMessageLength_decode_xer;
xer_type_encoder_f DispatcherMessageLength_encode_xer;
per_type_decoder_f DispatcherMessageLength_decode_uper;
per_type_encoder_f DispatcherMessageLength_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DispatcherMessageLength_H_ */
#include <asn_internal.h>
