/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DispatcherHeader"
 * 	found in "Dispatcher_Header.asn"
 * 	`asn1c -gen-PER`
 */

#include "DispatcherHeader.h"

static asn_TYPE_member_t asn_MBR_DispatcherHeader_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DispatcherHeader, protocolVersion),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolVersion,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"protocolVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DispatcherHeader, dispatcherMessageLength),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DispatcherMessageLength,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dispatcherMessageLength"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DispatcherHeader, dispatcherBodyEncoding),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DispatcherBodyEncoding,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dispatcherBodyEncoding"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DispatcherHeader, idType),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IdType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"idType"
		},
	{ ATF_POINTER, 2, offsetof(struct DispatcherHeader, tspTboxId),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TspTboxId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tspTboxId"
		},
	{ ATF_POINTER, 1, offsetof(struct DispatcherHeader, tspTboxSn),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TspTboxSn,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tspTboxSn"
		},
};
static const int asn_MAP_DispatcherHeader_oms_1[] = { 4, 5 };
static const ber_tlv_tag_t asn_DEF_DispatcherHeader_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DispatcherHeader_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* protocolVersion */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dispatcherMessageLength */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dispatcherBodyEncoding */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* idType */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* tspTboxId */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* tspTboxSn */
};
static asn_SEQUENCE_specifics_t asn_SPC_DispatcherHeader_specs_1 = {
	sizeof(struct DispatcherHeader),
	offsetof(struct DispatcherHeader, _asn_ctx),
	asn_MAP_DispatcherHeader_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_DispatcherHeader_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DispatcherHeader = {
	"DispatcherHeader",
	"DispatcherHeader",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DispatcherHeader_tags_1,
	sizeof(asn_DEF_DispatcherHeader_tags_1)
		/sizeof(asn_DEF_DispatcherHeader_tags_1[0]), /* 1 */
	asn_DEF_DispatcherHeader_tags_1,	/* Same as above */
	sizeof(asn_DEF_DispatcherHeader_tags_1)
		/sizeof(asn_DEF_DispatcherHeader_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DispatcherHeader_1,
	6,	/* Elements count */
	&asn_SPC_DispatcherHeader_specs_1	/* Additional specs */
};

