/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DispatcherHeader"
 * 	found in "Dispatcher_Header.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_DispatcherHeader_H_
#define	_DispatcherHeader_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolVersion.h"
#include "DispatcherMessageLength.h"
#include "DispatcherBodyEncoding.h"
#include "IdType.h"
#include "TspTboxId.h"
#include "TspTboxSn.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DispatcherHeader */
typedef struct DispatcherHeader {
	ProtocolVersion_t	 protocolVersion;
	DispatcherMessageLength_t	 dispatcherMessageLength;
	DispatcherBodyEncoding_t	 dispatcherBodyEncoding;
	IdType_t	 idType;
	TspTboxId_t	*tspTboxId	/* OPTIONAL */;
	TspTboxSn_t	*tspTboxSn	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DispatcherHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DispatcherHeader;

#ifdef __cplusplus
}
#endif

#endif	/* _DispatcherHeader_H_ */
#include <asn_internal.h>
