/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DispatcherHeader"
 * 	found in "Dispatcher_Header.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_IdType_H_
#define	_IdType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IdType */
typedef long	 IdType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IdType;
asn_struct_free_f IdType_free;
asn_struct_print_f IdType_print;
asn_constr_check_f IdType_constraint;
ber_type_decoder_f IdType_decode_ber;
der_type_encoder_f IdType_encode_der;
xer_type_decoder_f IdType_decode_xer;
xer_type_encoder_f IdType_encode_xer;
per_type_decoder_f IdType_decode_uper;
per_type_encoder_f IdType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _IdType_H_ */
#include <asn_internal.h>
