/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DispatcherHeader"
 * 	found in "Dispatcher_Header.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_ProtocolVersion_H_
#define	_ProtocolVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolVersion */
typedef long	 ProtocolVersion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolVersion;
asn_struct_free_f ProtocolVersion_free;
asn_struct_print_f ProtocolVersion_print;
asn_constr_check_f ProtocolVersion_constraint;
ber_type_decoder_f ProtocolVersion_decode_ber;
der_type_encoder_f ProtocolVersion_encode_der;
xer_type_decoder_f ProtocolVersion_decode_xer;
xer_type_encoder_f ProtocolVersion_encode_xer;
per_type_decoder_f ProtocolVersion_decode_uper;
per_type_encoder_f ProtocolVersion_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolVersion_H_ */
#include <asn_internal.h>
