/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DispatcherHeader"
 * 	found in "Dispatcher_Header.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_TspTboxId_H_
#define	_TspTboxId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TspTboxId */
typedef IA5String_t	 TspTboxId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TspTboxId;
asn_struct_free_f TspTboxId_free;
asn_struct_print_f TspTboxId_print;
asn_constr_check_f TspTboxId_constraint;
ber_type_decoder_f TspTboxId_decode_ber;
der_type_encoder_f TspTboxId_encode_der;
xer_type_decoder_f TspTboxId_decode_xer;
xer_type_encoder_f TspTboxId_encode_xer;
per_type_decoder_f TspTboxId_decode_uper;
per_type_encoder_f TspTboxId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TspTboxId_H_ */
#include <asn_internal.h>
