/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DispatcherBody"
 * 	found in "Dispatcher_Body.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_AckMessageCounter_H_
#define	_AckMessageCounter_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AckMessageCounter */
typedef long	 AckMessageCounter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AckMessageCounter;
asn_struct_free_f AckMessageCounter_free;
asn_struct_print_f AckMessageCounter_print;
asn_constr_check_f AckMessageCounter_constraint;
ber_type_decoder_f AckMessageCounter_decode_ber;
der_type_encoder_f AckMessageCounter_encode_der;
xer_type_decoder_f AckMessageCounter_decode_xer;
xer_type_encoder_f AckMessageCounter_encode_xer;
per_type_decoder_f AckMessageCounter_decode_uper;
per_type_encoder_f AckMessageCounter_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AckMessageCounter_H_ */
#include <asn_internal.h>
