/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DispatcherBody"
 * 	found in "Dispatcher_Body.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_ApplicationId_H_
#define	_ApplicationId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ApplicationId */
typedef IA5String_t	 ApplicationId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ApplicationId;
asn_struct_free_f ApplicationId_free;
asn_struct_print_f ApplicationId_print;
asn_constr_check_f ApplicationId_constraint;
ber_type_decoder_f ApplicationId_decode_ber;
der_type_encoder_f ApplicationId_encode_der;
xer_type_decoder_f ApplicationId_decode_xer;
xer_type_encoder_f ApplicationId_encode_xer;
per_type_decoder_f ApplicationId_decode_uper;
per_type_encoder_f ApplicationId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ApplicationId_H_ */
#include <asn_internal.h>
