/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ApplicationActivation"
 * 	found in "Application_Activation.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Iccid_H_
#define	_Iccid_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Iccid */
typedef IA5String_t	 Iccid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Iccid;
asn_struct_free_f Iccid_free;
asn_struct_print_f Iccid_print;
asn_constr_check_f Iccid_constraint;
ber_type_decoder_f Iccid_decode_ber;
der_type_encoder_f Iccid_encode_der;
xer_type_decoder_f Iccid_decode_xer;
xer_type_encoder_f Iccid_encode_xer;
per_type_decoder_f Iccid_decode_uper;
per_type_encoder_f Iccid_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Iccid_H_ */
#include <asn_internal.h>
