/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ApplicationActivation"
 * 	found in "Application_Activation.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_OtaNewSecKeyReq_H_
#define	_OtaNewSecKeyReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SecKeyAndTboxSn.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OtaNewSecKeyReq */
typedef struct OtaNewSecKeyReq {
	SecKeyAndTboxSn_t	 secKeyAndTboxSn;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OtaNewSecKeyReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtaNewSecKeyReq;

#ifdef __cplusplus
}
#endif

#endif	/* _OtaNewSecKeyReq_H_ */
#include <asn_internal.h>
