/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ApplicationActivation"
 * 	found in "Application_Activation.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_OtaNewPubKeyRes_H_
#define	_OtaNewPubKeyRes_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PublicKeyGranted.h"
#include "PublicKey.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OtaNewPubKeyRes */
typedef struct OtaNewPubKeyRes {
	PublicKeyGranted_t	 publicKeyGranted;
	PublicKey_t	*publicKey	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OtaNewPubKeyRes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtaNewPubKeyRes;

#ifdef __cplusplus
}
#endif

#endif	/* _OtaNewPubKeyRes_H_ */
#include <asn_internal.h>
