/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ApplicationActivation"
 * 	found in "Application_Activation.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_PublicKeyGranted_H_
#define	_PublicKeyGranted_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PublicKeyGranted */
typedef BOOLEAN_t	 PublicKeyGranted_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PublicKeyGranted;
asn_struct_free_f PublicKeyGranted_free;
asn_struct_print_f PublicKeyGranted_print;
asn_constr_check_f PublicKeyGranted_constraint;
ber_type_decoder_f PublicKeyGranted_decode_ber;
der_type_encoder_f PublicKeyGranted_encode_der;
xer_type_decoder_f PublicKeyGranted_decode_xer;
xer_type_encoder_f PublicKeyGranted_encode_xer;
per_type_decoder_f PublicKeyGranted_decode_uper;
per_type_encoder_f PublicKeyGranted_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PublicKeyGranted_H_ */
#include <asn_internal.h>
