/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ApplicationActivation"
 * 	found in "Application_Activation.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SecKeyReq_H_
#define	_SecKeyReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SecKeyReq */
typedef BOOLEAN_t	 SecKeyReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecKeyReq;
asn_struct_free_f SecKeyReq_free;
asn_struct_print_f SecKeyReq_print;
asn_constr_check_f SecKeyReq_constraint;
ber_type_decoder_f SecKeyReq_decode_ber;
der_type_encoder_f SecKeyReq_encode_der;
xer_type_decoder_f SecKeyReq_decode_xer;
xer_type_encoder_f SecKeyReq_encode_xer;
per_type_decoder_f SecKeyReq_decode_uper;
per_type_encoder_f SecKeyReq_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SecKeyReq_H_ */
#include <asn_internal.h>
