/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ApplicationActivation"
 * 	found in "Application_Activation.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SimInfo_H_
#define	_SimInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SimInfo */
typedef IA5String_t	 SimInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SimInfo;
asn_struct_free_f SimInfo_free;
asn_struct_print_f SimInfo_print;
asn_constr_check_f SimInfo_constraint;
ber_type_decoder_f SimInfo_decode_ber;
der_type_encoder_f SimInfo_encode_der;
xer_type_decoder_f SimInfo_decode_xer;
xer_type_encoder_f SimInfo_encode_xer;
per_type_decoder_f SimInfo_decode_uper;
per_type_encoder_f SimInfo_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SimInfo_H_ */
#include <asn_internal.h>
