/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ApplicationActivation"
 * 	found in "Application_Activation.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_VinCode_H_
#define	_VinCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VinCode */
typedef IA5String_t	 VinCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VinCode;
asn_struct_free_f VinCode_free;
asn_struct_print_f VinCode_print;
asn_constr_check_f VinCode_constraint;
ber_type_decoder_f VinCode_decode_ber;
der_type_encoder_f VinCode_encode_der;
xer_type_decoder_f VinCode_decode_xer;
xer_type_encoder_f VinCode_encode_xer;
per_type_decoder_f VinCode_decode_uper;
per_type_encoder_f VinCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VinCode_H_ */
#include <asn_internal.h>
